version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Paris
      - PASSWORD=Password01
      - SUDO_PASSWORD=SudoPassword
    volumes:
      - /mnt/nas/containers/code-server:/config
      - /mnt/nas:/nas
    ports:
      - 8443:8443
    restart: unless-stopped