version: '3.3'
services:
  app:
    volumes:
    - /mnt/nas/containers/dashy/config:/var/www/html/config/
    - /mnt/nas/containers/dashy/img:/var/www/html/img/
    ports:
    - '8092:8080'
    user: "1000:100"
    build:
      context: https://github.com/gaetan-puleo/dashy.git#main
      dockerfile: docker/Dockerfile