# This is just an example. Customize it to your needs.

version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_BASEURL: ""
      ND_ENABLETRANSCODINGCONFIG: true
    volumes:
      - "/mnt/nas/containers/navidrome/data:/data"
      # - "/mnt/nas/local/common/music/:/music:ro"
      - "/mnt/nas/mediatest/downloads:/music:ro"